import { publicBaseUrl } from './newsletter.js';

// Self-service cancellation of an event registration. Each registration row
// carries its own secret `cancel_token` (generated by the database default,
// migration 0015); the confirmation and reminder emails link to the page that
// spends it. Holding the link is the authorization — there is no login.

export const CANCEL_TOKEN_RE = /^[a-f0-9]{64}$/;

export function isCancelToken(value) {
  return typeof value === 'string' && CANCEL_TOKEN_RE.test(value);
}

export function registrationCancelUrl(token) {
  return `${publicBaseUrl()}/avmelding?token=${encodeURIComponent(token)}`;
}

// Today's date in Oslo as YYYY-MM-DD, the format events.date is stored in.
export function osloToday(now = new Date()) {
  const parts = new Intl.DateTimeFormat('en-CA', {
    timeZone: 'Europe/Oslo',
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
  }).formatToParts(now);
  const values = Object.fromEntries(parts.map((part) => [part.type, part.value]));
  return `${values.year}-${values.month}-${values.day}`;
}

// A registration can be cancelled up to and including the day of the event.
// Afterwards the row is history (and the retention cron removes it in time).
export function isCancellationOpen(eventDate, now = new Date()) {
  if (typeof eventDate !== 'string' || !eventDate) return false;
  return eventDate.slice(0, 10) >= osloToday(now);
}

// The paragraph the registration emails end with. Rows written before
// migration 0015 have no token, so they keep the old "reply to this email"
// instruction instead of a broken link.
export function cancellationText({ language, cancelToken }) {
  const isNorwegian = language !== 'en';
  if (!isCancelToken(cancelToken)) {
    return isNorwegian
      ? 'Kan du likevel ikke komme? Gi beskjed til FAU ved å svare på denne e-posten.'
      : 'Can no longer attend? Let FAU know by replying to this email.';
  }
  const link = registrationCancelUrl(cancelToken);
  return isNorwegian
    ? `Kan du likevel ikke komme? Meld deg av her: ${link}`
    : `Can no longer attend? Cancel your registration here: ${link}`;
}
