-- Self-service cancellation: every registration carries its own secret token,
-- and the confirmation and reminder emails link to /avmelding?token=… so a
-- parent can cancel without contacting FAU.
--
-- The token is generated by the database default, so it is present on every
-- row whichever version of api/registrations.js inserted it. That makes this
-- migration safe to apply before the matching code is deployed. Two random
-- UUIDs with the dashes removed give 64 lowercase hex characters (244 random
-- bits from pg_strong_random) — the same shape as the newsletter tokens.
-- gen_random_uuid() is built into PostgreSQL 13+, no extension needed.
-- Existing registrations are backfilled so their reminders carry a link too.
-- Safe to rerun.

ALTER TABLE event_registrations
  ADD COLUMN IF NOT EXISTS cancel_token text;

ALTER TABLE event_registrations
  ALTER COLUMN cancel_token
  SET DEFAULT replace(gen_random_uuid()::text || gen_random_uuid()::text, '-', '');

UPDATE event_registrations
SET cancel_token = replace(gen_random_uuid()::text || gen_random_uuid()::text, '-', '')
WHERE cancel_token IS NULL;

ALTER TABLE event_registrations
  ALTER COLUMN cancel_token SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS event_registrations_cancel_token_idx
  ON event_registrations (cancel_token);
